[package]
edition = "2021"
name = "grammar"
version = "0.1.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "../library/macros" }
libc = "0.2.138"

[build-dependencies]
cc = "1.0.77"
